version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: degitale
      MONGO_INITDB_ROOT_PASSWORD: factory
      MONGO_INITDB_DATABASE: DF

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://degitale:factory@mongodb:27017/DF"
      JWT_SECRET: "sfsfh8HDSFHSD_çfdiuqhrue&w=majority"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
